### ISSUE TITLE
com.google.android.exoplayer2.ParserException: Failed to parse the playlist, could not identify any tags.

### ISSUE THREAD

**Issue by newandroidboy88** [ayalus/ExoPlayer-2-Example#1]
Period release failed.
                                                                                     java.lang.NullPointerException: Attempt to get length of null array
                                                                                         at com.google.android.exoplayer2.source.hls.HlsMediaPeriod.release(HlsMediaPeriod.java:109)
                                                                                         at com.google.android.exoplayer2.source.hls.HlsMediaSource.releasePeriod(HlsMediaSource.java:85)
                                                                                         at com.google.android.exoplayer2.source.LoopingMediaSource.releasePeriod(LoopingMediaSource.java:86)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal$MediaPeriodHolder.release(ExoPlayerImplInternal.java:1283)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.releasePeriodHoldersFrom(ExoPlayerImplInternal.java:1091)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:629)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.stopInternal(ExoPlayerImplInternal.java:600)
                                                                                         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:311)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                         at com.google.android.exoplayer2.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)

**Comment by ayalus** [comment]
might be the source of m3u8 or device running it. i updated the exoplayer version. you may try again.
